---
apiVersion: v1
data:
  Dockerfile: |
    FROM registry.fedoraproject.org/fedora:36
    RUN uname -a | tee /uname && \
      echo "i'm arch-agnostic" > /etc/arch-agnostic
  Dockerfile.0: |
    FROM image-registry.openshift-image-registry.svc:5000/default/built-image:amd64
    RUN echo "i'm amd64-specific" > /etc/amd64-specific
  Dockerfile.1: |
    FROM image-registry.openshift-image-registry.svc:5000/default/built-image:arm64
    RUN echo "i'm arm64-specific" > /etc/arm64-specific
  Dockerfile.2: |
    FROM image-registry.openshift-image-registry.svc:5000/default/built-image:ppc64le
    RUN echo "i'm ppc64le-specific" > /etc/ppc64le-specific
  Dockerfile.3: |
    FROM image-registry.openshift-image-registry.svc:5000/default/built-image:s390x
    RUN echo "i'm s390x-specific" > /etc/s390x-specific
kind: ConfigMap
metadata:
  name: dockerfile
---
apiVersion: v1
kind: ConfigMap
data:
  0: amd64
  1: arm64
  2: ppc64le
  3: s390x
metadata:
  name: job-index
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: built-image
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/default/built-image
---
apiVersion: batch/v1
kind: Job
metadata:
  name: image-build
spec:
  completions: 4
  parallelism: 4
  completionMode: Indexed
  template:
    spec:
      containers:
        - name: image-build
          image: image-registry.openshift-image-registry.svc:5000/default/buildah-img:latest
          workdir: /home/build
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -xeuo

              pwd
              id
              whoami

              target_arch="$(cat /tmp/job-index/$JOB_COMPLETION_INDEX)"
              arch_agnostic_dockerfile="$PWD/Dockerfile"
              arch_specific_dockerfile="$PWD/Dockerfile.${target_arch}"

              cp /tmp/dockerfile/Dockerfile "$arch_agnostic_dockerfile"
              cp "/tmp/dockerfile/Dockerfile.${JOB_COMPLETION_INDEX}" "$arch_specific_dockerfile"

              tag="image-registry.openshift-image-registry.svc:5000/default/built-image:${target_arch}"

              buildah --version
              # Build an image using the architecture-agnostic Dockerfile which should work on all architectures.
              buildah bud --arch "$target_arch" --storage-driver vfs --tag "$tag" --file="${arch_agnostic_dockerfile}" .
              # Build an image using the architecture-specific Dockerfile which only works on a given architecture.
              buildah bud --arch "$target_arch" --storage-driver vfs --tag "$tag" --file="${arch_specific_dockerfile}" .

              buildah push --storage-driver vfs --authfile=/home/build/.docker/config.json --cert-dir /var/run/secrets/kubernetes.io/serviceaccount "$tag"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          serviceAccount: builder
          volumeMounts:
            - name: dockerfile
              mountPath: /tmp/dockerfile
            - name: job-index
              mountPath: /tmp/job-index
            - name: registry-creds
              mountPath: /home/build/.docker
      restartPolicy: Never
      volumes:
        - name: dockerfile
          configMap:
            name: dockerfile
        - name: job-index
          configMap:
            name: job-index
        - name: registry-creds
          secret:
            secretName: imagestream-push-secrets
            items:
              - key: .dockerconfigjson
                path: config.json
