---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: buildah-img
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/default/buildah-img
---
apiVersion: build.openshift.io/v1
kind: Build
metadata:
  name: buildah-image-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: buildah-img:latest
  postCommit: {}
  resources: {}
  serviceAccount: builder
  source:
    dockerfile: |
      FROM quay.io/buildah/stable:latest
      RUN dnf install -y qemu-user-static && \
        chmod -R 755 /etc/containers
      ENV HOME=/home/build
      USER build
      WORKDIR /home/build
    type: Dockerfile
  strategy:
    dockerStrategy: {}
    type: Docker
